[package]
name = "ecobot"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["server", "client", "lib"]

[workspace.dependencies]
teloxide = { version = "0.13", features = ["macros"] }
log = "0.4"
pretty_env_logger = "0.5.0"
tokio = { version = "1.8", features = ["rt-multi-thread", "macros"] }
