TELOXIDE_TOKEN = "111:222dfsaf"
SENTRY_URL = "https://somenumbers@idtext.ingest.de.sentry.io/idtext"
URL = "localhost"
PORT = "8000"
DBNAME = "somedb"
NAMESPACE = "namespace"
USERNAME = "username"
PASSWORD = "password"
